(function(){'use strict';
const launch=document.createElement('button');launch.id='lm-launch';launch.textContent='本地修改';document.body.appendChild(launch);
const panel=document.createElement('div');panel.id='lm-panel';panel.hidden=true;
panel.innerHTML='<section id="lm-card" role="dialog" aria-modal="true" aria-label="本地修改面板"><button id="lm-close">关闭</button><h2>本地修改面板</h2><p>创建人物并进入生涯后使用。修改前自动备份；能力和潜力上限 99。</p><label>资金<input id="lm-money" type="number" min="0" max="1000000000"></label><label>技能点<input id="lm-sp" type="number" min="0" max="99999"></label><label>所有能力设为<input id="lm-ability" type="number" min="1" max="99" placeholder="留空则不改"></label><label>所有潜力设为<input id="lm-potential" type="number" min="1" max="99" placeholder="留空则不改"></label><label><span>恢复伤病和士气</span><input id="lm-heal" type="checkbox"></label><button id="lm-apply">应用并保存</button><div class="lm-grid"><button id="lm-export">导出存档</button><button id="lm-import">导入存档</button><button id="lm-undo">撤回上次修改</button><button id="lm-refresh">读取当前数值</button></div><input id="lm-file" type="file" accept="application/json,.json" hidden><div id="lm-status" role="status"></div><p>本地存档保存在当前浏览器。线上排行榜、虎扑云存档和广告奖励不在离线版本中提供。</p></section>';
document.body.appendChild(panel);const el=id=>document.getElementById('lm-'+id),msg=s=>el('status').textContent=s;
function state(){if(!window.State||!State.data||!State.data.player||!State.data.clubId||State.isNew)throw Error('请先创建人物并进入生涯，再使用修改功能。');return State.data}
function backup(){const raw=State._packSaveJson();localStorage.setItem('football_local_mod_backup',raw);return raw}
function refresh(){try{const d=state();el('money').value=d.money;el('sp').value=d.skillPoints;msg('已读取：'+d.player.name)}catch(e){msg(e.message)}}
function number(id,min,max,optional){const v=el(id).value.trim();if(optional&&!v)return null;const n=Number(v);if(!v||!Number.isFinite(n)||n<min||n>max)throw Error('请输入有效数值：'+id+'（'+min+'–'+max+'）');return Math.floor(n)}
function download(raw,name){const url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function persist(){State.save(true);if(localStorage.getItem(State._lsMain())!==State._packSaveJson())throw Error('浏览器存档写入未确认，请导出存档备份。')}
launch.onclick=()=>{panel.hidden=false;refresh();el('close').focus()};el('close').onclick=()=>{panel.hidden=true;launch.focus()};panel.onclick=e=>{if(e.target===panel)el('close').click()};document.addEventListener('keydown',e=>{if(e.key==='Escape')el('close').click()});el('refresh').onclick=refresh;
el('apply').onclick=()=>{try{const d=state(),money=number('money',0,1e9),sp=number('sp',0,99999),ability=number('ability',1,99,true),pot=number('potential',1,99,true);backup();d.money=money;d.skillPoints=sp;const attrs=d.player.attrs||{};if(ability!==null){for(const k of Object.keys(attrs)){attrs[k]=ability;if(d.player.pot&&typeof d.player.pot[k]==='number')d.player.pot[k]=Math.max(d.player.pot[k],ability)}}if(pot!==null&&d.player.pot){for(const k of Object.keys(d.player.pot))if(typeof d.player.pot[k]==='number')d.player.pot[k]=Math.max(pot,attrs[k]||1)}if(el('heal').checked){d.injuryDays=0;d.morale=100}persist();if(window.Hub&&Hub.refresh)Hub.refresh(State);msg('修改已保存。潜力不会低于当前能力。')}catch(e){msg(e.message)}};
el('export').onclick=()=>{try{state();persist();download(State._packSaveJson(),'football-career-save.json');msg('已导出当前存档。')}catch(e){msg(e.message)}};
function validate(d){if(!d||Array.isArray(d)||d.meta?.dataset!=='real-v1'||!d.player||!d.clubId||!d.date||!Number.isFinite(d.money)||!d.player.attrs||typeof d.player.name!=='string')throw Error('这不是有效的本游戏生涯存档。');if(!window.teamById||!teamById(d.clubId))throw Error('存档俱乐部不存在。');return d}
function restore(raw){let d=validate(JSON.parse(raw));const old=State.data;try{State.data=d;State._unpackLoaded(d);State.isNew=false;persist()}catch(e){State.data=old;throw e}location.reload()}
el('import').onclick=()=>el('file').click();el('file').onchange=async()=>{const f=el('file').files[0];if(!f)return;try{if(f.size>25*1024*1024)throw Error('存档文件过大。');const raw=await f.text();validate(JSON.parse(raw));if(!confirm('导入将替换当前生涯，当前进度会先备份。继续？'))return;if(State.data?.player&&!State.isNew)backup();restore(raw)}catch(e){msg(e.message)}finally{el('file').value=''}};
el('undo').onclick=()=>{try{const raw=localStorage.getItem('football_local_mod_backup');if(!raw)throw Error('还没有修改备份。');validate(JSON.parse(raw));if(confirm('恢复修改前的存档？'))restore(raw)}catch(e){msg(e.message)}};
})();
